import { Redis } from '@upstash/redis';
import { Resend } from 'resend';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { email, aiResponse, totals, results } = body;

    const dbUrl = process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL;
    const dbToken = process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN;
    const resendKey = process.env.RESEND_API_KEY;

    if (!dbUrl || !dbToken) return new Response("DB Keys missing", { status: 500 });

    const redis = new Redis({ url: dbUrl, token: dbToken });
    const shareId = Math.random().toString(36).substring(2, 9);
    
    await redis.set(`audit:${shareId}`, { email, aiResponse, totals, results, createdAt: Date.now() });

    if (resendKey) {
      const resend = new Resend(resendKey);
      const host = req.headers.get('host') || 'vantage.vercel.app';
      const protocol = host.includes('localhost') ? 'http' : 'https';

      await resend.emails.send({
        from: 'onboarding@resend.dev',
        to: email,
        subject: 'Your Vantage AI Audit is Ready',
        html: `
          <div style="font-family: sans-serif; max-w: 600px; margin: 20px auto; border: 1px solid #eee; padding: 40px; border-radius: 12px;">
            <h2 style="color: #111; margin-bottom: 8px;">Vantage Audit Complete</h2>
            <p style="color: #666; font-size: 16px;">We found <strong>$${totals.savings}</strong> in potential monthly savings in your AI stack.</p>
            <div style="margin: 32px 0;">
              <a href="${protocol}://${host}/audit/${shareId}" style="background: #111; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 14px;">View Full Executive Report</a>
            </div>
            <p style="color: #999; font-size: 12px;">This audit was generated by Vantage.</p>
          </div>
        `
      });
    }

    return new Response(JSON.stringify({ shareId }), { status: 200 });
  } catch (error: any) {
    return new Response(error.message, { status: 500 });
  }
}
